import React, { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { apiRequest, dateTime, money } from '../api';
import { AdminLayout } from '../components/AdminLayout';

const ORDER_LABEL = {PENDING:'Chờ xác nhận',CONFIRMED:'Đã xác nhận',COOKING:'Đang nấu',COMPLETED:'Hoàn thành',CANCELLED:'Đã hủy'};
const PRODUCT_LABEL = {PUBLISHED:'Đang hiển thị',DRAFT:'Bản nháp',HIDDEN:'Tạm ẩn'};
const ROLE_LABEL = {USER:'Khách hàng',INSTRUCTOR:'Người bán',ADMIN:'Quản trị viên',COMPANY_ADMIN:'Quản trị công ty'};

function Notice({message}) { return message ? <div className={`auth-message ${message.type||'error'}`}>{message.text}</div> : null; }
function Loading(){return <div className="card">Đang tải dữ liệu...</div>;}
function Pager({data,onPage}){if(!data||data.totalPages<=1)return null;return <div className="between"><span className="small muted">Trang {data.number+1} / {data.totalPages}</span><div className="row"><button className="btn secondary sm" disabled={data.first} onClick={()=>onPage(data.number-1)}>← Trước</button><button className="btn secondary sm" disabled={data.last} onClick={()=>onPage(data.number+1)}>Sau →</button></div></div>}
function statusClass(status){if(['PENDING','COOKING','DRAFT'].includes(status))return 'gold';if(['CANCELLED'].includes(status))return 'red';if(['COMPLETED','HIDDEN'].includes(status))return 'gray';return '';}

export function AdminDashboardPage(){
  const [data,setData]=useState(null); const [message,setMessage]=useState(null);
  useEffect(()=>{apiRequest('/api/admin/dashboard').then(setData).catch(e=>setMessage({text:e.message}));},[]);
  return <AdminLayout title="Tổng quan" lead="Theo dõi nhanh hoạt động của GO Cook từ dữ liệu thật trong hệ thống."><Notice message={message}/>{!data?<Loading/>:<><div className="grid grid-4"><Metric title="Người dùng" value={data.userCount}/><Metric title="Sản phẩm đang hiển thị" value={data.productCount}/><Metric title="Đơn hàng" value={data.orderCount}/><Metric title="Doanh thu hoàn thành" value={money(data.completedRevenue)}/></div><section className="card stack"><div className="between"><h3>Đơn hàng gần đây</h3><Link className="text-link" to="/admin/orders">Xem tất cả</Link></div><div className="table-wrap"><table><thead><tr><th>Mã đơn</th><th>Khách hàng</th><th>Thực đơn</th><th>Ngày nấu</th><th>Trạng thái</th></tr></thead><tbody>{(data.recentOrders||[]).map(o=><tr key={o.id}><td><Link className="text-link" to={`/admin/order-detail?id=${o.id}`}>{o.orderCode}</Link></td><td>{o.customerName}</td><td>{o.productName}</td><td>{o.scheduledAtDisplay||dateTime(o.scheduledAt)}</td><td><span className={`badge ${statusClass(o.status)}`}>{ORDER_LABEL[o.status]||o.status}</span></td></tr>)}</tbody></table></div></section></>}</AdminLayout>;
}
function Metric({title,value}){return <article className="card metric"><p className="small muted">{title}</p><p className="value green">{value}</p></article>}

export function AdminUsersPage(){
  const [params,setParams]=useSearchParams();
  const [data,setData]=useState(null); const [message,setMessage]=useState(null);
  const q=params.get('q')||'', role=params.get('role')||'', status=params.get('status')||'', page=Number(params.get('page')||0), size=Number(params.get('size')||10);
  const load=()=>apiRequest(`/api/admin/users?q=${encodeURIComponent(q)}&role=${encodeURIComponent(role)}&status=${encodeURIComponent(status)}&page=${page}&size=${size}`).then(setData).catch(e=>setMessage({text:e.message}));
  useEffect(load,[q,role,status,page,size]);
  function apply(e){e.preventDefault();const f=new FormData(e.currentTarget);setParams({q:f.get('q')||'',role:f.get('role')||'',status:f.get('status')||'',size:f.get('size')||'10',page:'0'});}
  async function toggle(id){try{await apiRequest(`/api/admin/users/${id}/toggle`,{method:'PATCH'});setMessage({type:'success',text:'Đã cập nhật trạng thái tài khoản.'});load();}catch(e){setMessage({text:e.message});}}
  return <AdminLayout title="Quản lý người dùng" lead="Tìm kiếm, phân quyền và khóa/mở tài khoản."><Notice message={message}/><form className="card grid grid-4" onSubmit={apply}><label className="field">Tìm người dùng<input name="q" defaultValue={q} placeholder="Tên hoặc email"/></label><label className="field">Vai trò<select name="role" defaultValue={role}><option value="">Tất cả</option>{['USER','INSTRUCTOR','ADMIN','COMPANY_ADMIN'].map(x=><option key={x}>{x}</option>)}</select></label><label className="field">Trạng thái<select name="status" defaultValue={status}><option value="">Tất cả</option><option value="active">Đang hoạt động</option><option value="inactive">Đã khóa</option></select></label><label className="field">Số dòng<select name="size" defaultValue={size}><option>10</option><option>20</option><option>50</option></select></label><button className="btn" type="submit">Lọc người dùng</button></form>{!data?<Loading/>:<section className="card stack"><div className="table-wrap"><table><caption>Hiển thị {data.numberOfElements} / {data.totalElements} người dùng</caption><thead><tr><th>Người dùng</th><th>Email</th><th>Vai trò</th><th>Trạng thái</th><th>Ngày tạo</th><th>Thao tác</th></tr></thead><tbody>{data.content.map(u=><tr key={u.id}><td><strong>{u.username}</strong></td><td>{u.email}</td><td>{u.roleLabel||ROLE_LABEL[u.role]}</td><td><span className={`badge ${u.active?'':'red'}`}>{u.active?'Hoạt động':'Đã khóa'}</span></td><td>{u.createdAtDisplay||'—'}</td><td><div className="row"><Link className="text-link" to={`/admin/user-edit?id=${u.id}`}>Sửa</Link><button className="text-link" type="button" onClick={()=>toggle(u.id)}>{u.active?'Khóa':'Mở'}</button></div></td></tr>)}</tbody></table></div><Pager data={data} onPage={p=>setParams({q,role,status,size:String(size),page:String(p)})}/></section>}</AdminLayout>;
}

export function AdminUserEditPage(){
  const [params]=useSearchParams(); const navigate=useNavigate(); const id=params.get('id');
  const [data,setData]=useState(null); const [form,setForm]=useState(null); const [message,setMessage]=useState(null); const [busy,setBusy]=useState(false);
  useEffect(()=>{apiRequest(`/api/admin/users/${id}`).then(d=>{setData(d);setForm({username:d.user.username,role:d.user.role,active:d.user.active});}).catch(e=>setMessage({text:e.message}));},[id]);
  async function save(e){e.preventDefault();setBusy(true);try{await apiRequest(`/api/admin/users/${id}`,{method:'PUT',body:JSON.stringify(form)});navigate('/admin/users',{replace:true});}catch(e){setMessage({text:e.message});}finally{setBusy(false);}}
  return <AdminLayout title="Chỉnh sửa người dùng" lead="Cập nhật tên hiển thị, vai trò và trạng thái tài khoản."><Notice message={message}/>{!form?<Loading/>:<form className="card stack" onSubmit={save}><label className="field">Email<input value={data.user.email} readOnly/></label><label className="field">Tên hiển thị<input value={form.username} onChange={e=>setForm({...form,username:e.target.value})} required/></label><label className="field">Vai trò<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}>{(data.roles||[]).map(r=><option key={r} value={r}>{ROLE_LABEL[r]||r}</option>)}</select></label><label className="check"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/><span>Tài khoản đang hoạt động</span></label><div className="row"><button className="btn" disabled={busy}>{busy?'Đang lưu...':'Lưu thay đổi'}</button><Link className="btn secondary" to="/admin/users">Hủy</Link></div></form>}</AdminLayout>;
}

export function AdminProductsPage(){
  const [params,setParams]=useSearchParams(); const [data,setData]=useState(null); const [message,setMessage]=useState(null);
  const q=params.get('q')||'',category=params.get('category')||'',status=params.get('status')||'',page=Number(params.get('page')||0),size=Number(params.get('size')||10);
  const load=()=>apiRequest(`/api/admin/products?q=${encodeURIComponent(q)}&category=${encodeURIComponent(category)}&status=${encodeURIComponent(status)}&page=${page}&size=${size}`).then(setData).catch(e=>setMessage({text:e.message}));
  useEffect(load,[q,category,status,page,size]);
  function apply(e){e.preventDefault();const f=new FormData(e.currentTarget);setParams({q:f.get('q')||'',category:f.get('category')||'',status:f.get('status')||'',size:f.get('size')||'10',page:'0'});}
  async function toggle(id){try{await apiRequest(`/api/admin/products/${id}/toggle`,{method:'PATCH'});setMessage({type:'success',text:'Đã cập nhật trạng thái hiển thị.'});load();}catch(e){setMessage({text:e.message});}}
  return <AdminLayout title="Quản lý sản phẩm" lead="Quản lý thực đơn, giá và trạng thái hiển thị."><Notice message={message}/><div className="between"><span/><Link className="btn" to="/admin/product-new">+ Thêm thực đơn</Link></div><form className="card grid grid-4" onSubmit={apply}><label className="field">Tìm sản phẩm<input name="q" defaultValue={q}/></label><label className="field">Danh mục<select name="category" defaultValue={category}><option value="">Tất cả</option>{(data?.categories||[]).map(x=><option key={x}>{x}</option>)}</select></label><label className="field">Trạng thái<select name="status" defaultValue={status}><option value="">Tất cả</option>{['PUBLISHED','DRAFT','HIDDEN'].map(x=><option key={x} value={x}>{PRODUCT_LABEL[x]}</option>)}</select></label><label className="field">Số dòng<select name="size" defaultValue={size}><option>10</option><option>20</option><option>50</option></select></label><button className="btn">Lọc sản phẩm</button></form>{!data?<Loading/>:<section className="card stack"><div className="table-wrap"><table><caption>Hiển thị {data.numberOfElements} / {data.totalElements} sản phẩm</caption><thead><tr><th>Mã</th><th>Tên</th><th>Danh mục</th><th>Giá/người</th><th>Số khách</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{data.content.map(p=><tr key={p.id}><td>{p.displayCode||`SP-${p.id}`}</td><td><strong>{p.name}</strong></td><td>{p.category}</td><td>{money(p.unitPrice)}</td><td>{p.minGuests}–{p.maxGuests}</td><td><span className={`badge ${statusClass(p.status)}`}>{PRODUCT_LABEL[p.status]||p.status}</span></td><td><div className="row"><Link className="text-link" to={`/admin/product-edit?id=${p.id}`}>Sửa</Link><button className="text-link" type="button" onClick={()=>toggle(p.id)}>{p.status==='PUBLISHED'?'Ẩn':'Hiện'}</button></div></td></tr>)}</tbody></table></div><Pager data={data} onPage={p=>setParams({q,category,status,size:String(size),page:String(p)})}/></section>}</AdminLayout>;
}

function ProductForm({edit=false}){
  const [params]=useSearchParams(); const navigate=useNavigate(); const id=params.get('id'); const [options,setOptions]=useState({categories:[],statuses:[]}); const [message,setMessage]=useState(null); const [busy,setBusy]=useState(false);
  const [form,setForm]=useState({name:'',category:'Món miền Nam',unitPrice:'',minGuests:3,maxGuests:8,dishItems:'',description:'',imageUrl:'',status:'DRAFT'});
  useEffect(()=>{const url=edit?`/api/admin/products/${id}`:'/api/admin/products/options';apiRequest(url).then(d=>{setOptions({categories:d.categories||[],statuses:d.statuses||[]});if(edit&&d.product)setForm({name:d.product.name||'',category:d.product.category||'',unitPrice:d.product.unitPrice||'',minGuests:d.product.minGuests||3,maxGuests:d.product.maxGuests||8,dishItems:d.product.dishItems||'',description:d.product.description||'',imageUrl:d.product.imageUrl||'',status:d.product.status||'DRAFT'});}).catch(e=>setMessage({text:e.message}));},[edit,id]);
  async function save(e){e.preventDefault();setBusy(true);setMessage(null);const body={...form,unitPrice:Number(form.unitPrice),minGuests:Number(form.minGuests),maxGuests:Number(form.maxGuests)};try{await apiRequest(edit?`/api/admin/products/${id}`:'/api/admin/products',{method:edit?'PUT':'POST',body:JSON.stringify(body)});navigate('/admin/products',{replace:true});}catch(e){setMessage({text:e.message});}finally{setBusy(false);}}
  return <AdminLayout title={edit?'Chỉnh sửa sản phẩm':'Thêm sản phẩm'} lead="Thông tin thực đơn dùng cho khu vực quản trị."><Notice message={message}/><form className="card stack" onSubmit={save}><div className="grid grid-2"><label className="field">Tên thực đơn<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label className="field">Danh mục<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{options.categories.map(x=><option key={x}>{x}</option>)}</select></label><label className="field">Giá mỗi người<input type="number" min="0" value={form.unitPrice} onChange={e=>setForm({...form,unitPrice:e.target.value})} required/></label><label className="field">Trạng thái<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{['PUBLISHED','DRAFT','HIDDEN'].map(x=><option key={x} value={x}>{PRODUCT_LABEL[x]}</option>)}</select></label><label className="field">Khách tối thiểu<input type="number" min="1" value={form.minGuests} onChange={e=>setForm({...form,minGuests:e.target.value})}/></label><label className="field">Khách tối đa<input type="number" min="1" value={form.maxGuests} onChange={e=>setForm({...form,maxGuests:e.target.value})}/></label></div><label className="field">Danh sách món<textarea value={form.dishItems} onChange={e=>setForm({...form,dishItems:e.target.value})}/></label><label className="field">Mô tả<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="field">URL hình ảnh<input value={form.imageUrl} onChange={e=>setForm({...form,imageUrl:e.target.value})}/></label><div className="row"><button className="btn" disabled={busy}>{busy?'Đang lưu...':'Lưu sản phẩm'}</button><Link className="btn secondary" to="/admin/products">Hủy</Link></div></form></AdminLayout>;
}
export function AdminProductNewPage(){return <ProductForm/>} export function AdminProductEditPage(){return <ProductForm edit/>}

export function AdminOrdersPage(){
  const [params,setParams]=useSearchParams(); const [data,setData]=useState(null); const [message,setMessage]=useState(null);
  const q=params.get('q')||'',status=params.get('status')||'',from=params.get('from')||'',to=params.get('to')||'',page=Number(params.get('page')||0),size=Number(params.get('size')||10);
  const query=useMemo(()=>new URLSearchParams({q,status,page:String(page),size:String(size),...(from?{from}:{}),...(to?{to}:{})}).toString(),[q,status,from,to,page,size]);
  useEffect(()=>{apiRequest(`/api/admin/orders?${query}`).then(setData).catch(e=>setMessage({text:e.message}));},[query]);
  function apply(e){e.preventDefault();const f=new FormData(e.currentTarget);setParams({q:f.get('q')||'',status:f.get('status')||'',from:f.get('from')||'',to:f.get('to')||'',size:f.get('size')||'10',page:'0'});}
  return <AdminLayout title="Quản lý đơn hàng" lead="Tìm kiếm, lọc theo thời gian và cập nhật tiến trình các đơn đặt nấu."><Notice message={message}/><form className="card grid grid-3" onSubmit={apply}><label className="field">Tìm đơn<input name="q" defaultValue={q} placeholder="Mã đơn, khách, thực đơn hoặc đầu bếp"/></label><label className="field">Trạng thái<select name="status" defaultValue={status}><option value="">Tất cả</option>{Object.keys(ORDER_LABEL).map(x=><option key={x} value={x}>{ORDER_LABEL[x]}</option>)}</select></label><label className="field">Từ ngày<input type="date" name="from" defaultValue={from}/></label><label className="field">Đến ngày<input type="date" name="to" defaultValue={to}/></label><label className="field">Số dòng<select name="size" defaultValue={size}><option>10</option><option>20</option><option>50</option></select></label><button className="btn">Lọc đơn hàng</button></form>{!data?<Loading/>:<section className="card stack"><div className="table-wrap"><table><caption>Hiển thị {data.numberOfElements} / {data.totalElements} đơn hàng</caption><thead><tr><th>Mã đơn</th><th>Khách hàng</th><th>Thực đơn</th><th>Ngày nấu</th><th>Tổng tiền</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{data.content.map(o=><tr key={o.id}><td><strong>{o.orderCode}</strong></td><td>{o.customerName}</td><td>{o.productName}</td><td>{o.scheduledAtDisplay||dateTime(o.scheduledAt)}</td><td>{money(o.totalAmount)}</td><td><span className={`badge ${statusClass(o.status)}`}>{ORDER_LABEL[o.status]||o.status}</span></td><td><Link className="text-link" to={`/admin/order-detail?id=${o.id}`}>Chi tiết</Link></td></tr>)}</tbody></table></div><Pager data={data} onPage={p=>setParams({q,status,from,to,size:String(size),page:String(p)})}/></section>}</AdminLayout>;
}

export function AdminOrderDetailPage(){
  const [params]=useSearchParams(); const id=params.get('id'); const [data,setData]=useState(null); const [status,setStatus]=useState(''); const [note,setNote]=useState(''); const [message,setMessage]=useState(null); const [busy,setBusy]=useState(false);
  const load=()=>apiRequest(`/api/admin/orders/${id}`).then(d=>{setData(d);setStatus(d.order.status);setNote(d.order.internalNote||'');}).catch(e=>setMessage({text:e.message})); useEffect(load,[id]);
  async function save(e){e.preventDefault();setBusy(true);try{const d=await apiRequest(`/api/admin/orders/${id}`,{method:'PUT',body:JSON.stringify({status,internalNote:note})});setData(d);setStatus(d.order.status);setMessage({type:'success',text:d.message||'Đã cập nhật đơn hàng.'});}catch(e){setMessage({text:e.message});}finally{setBusy(false);}}
  if(!data)return <AdminLayout title="Chi tiết đơn hàng"><Notice message={message}/><Loading/></AdminLayout>; const o=data.order;
  return <AdminLayout title={`Đơn hàng ${o.orderCode}`} lead="Chi tiết và cập nhật tiến trình đơn đặt nấu."><Notice message={message}/><section className="card stack"><div className="grid grid-2"><Info k="Khách hàng" v={o.customerName}/><Info k="Email" v={o.customerEmail||'—'}/><Info k="Thực đơn" v={o.productName}/><Info k="Đầu bếp" v={o.chefName||'—'}/><Info k="Ngày nấu" v={o.scheduledAtDisplay||dateTime(o.scheduledAt)}/><Info k="Số khách" v={o.guestCount}/><Info k="Tổng tiền" v={money(o.totalAmount)}/><Info k="Địa chỉ" v={o.serviceAddress||'—'}/></div>{o.customerNote&&<div><p className="small muted">Ghi chú khách hàng</p><p>{o.customerNote}</p></div>}</section><form className="card stack" onSubmit={save}><label className="field">Trạng thái<select value={status} onChange={e=>setStatus(e.target.value)}>{(data.allowedStatuses||[]).map(x=><option key={x} value={x}>{ORDER_LABEL[x]||x}</option>)}</select></label><label className="field">Ghi chú nội bộ<textarea value={note} onChange={e=>setNote(e.target.value)}/></label><div className="row"><button className="btn" disabled={busy}>{busy?'Đang lưu...':'Cập nhật đơn hàng'}</button><Link className="btn secondary" to="/admin/orders">Quay lại</Link></div></form></AdminLayout>;
}
function Info({k,v}){return <div><p className="small muted">{k}</p><strong>{v}</strong></div>}

export function AdminStatisticsPage(){
  const today=new Date(); const to=today.toISOString().slice(0,10); const start=new Date(today.getFullYear(),today.getMonth()-5,1).toISOString().slice(0,10);
  const [from,setFrom]=useState(start); const [end,setEnd]=useState(to); const [data,setData]=useState(null); const [message,setMessage]=useState(null);
  const load=async()=>{setMessage(null);try{setData(await apiRequest(`/api/admin/statistics?from=${from}&to=${end}`));}catch(e){setMessage({text:e.message});}}; useEffect(()=>{load();},[]);
  const max=Math.max(1,...(data?.monthlyRevenue||[]).map(x=>Number(x.revenue||0)));
  const totalStatus=Object.values(data?.statusCounts||{}).reduce((a,b)=>a+Number(b),0)||1; const completed=Number(data?.statusCounts?.COMPLETED||0); const cancelled=Number(data?.statusCounts?.CANCELLED||0); const active=Math.max(0,totalStatus-cancelled);
  return <AdminLayout title="Thống kê nền tảng" lead="Theo dõi doanh thu, đơn đặt nấu và cơ cấu hoạt động của GO Cook."><Notice message={message}/><form className="card grid grid-3" onSubmit={e=>{e.preventDefault();load();}}><label className="field">Từ ngày<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="field">Đến ngày<input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label><div className="field"><span>&nbsp;</span><button className="btn">Xem thống kê</button></div></form>{!data?<Loading/>:<><div className="grid grid-4"><Metric title="Doanh thu hoàn thành" value={money(data.revenue)}/><Metric title="Đơn đặt nấu" value={data.orderCount}/><Metric title="Đầu bếp hoạt động" value={data.chefCount}/><Metric title="Người dùng" value={data.userCount}/></div><div className="grid grid-2"><figure className="card stack-sm"><figcaption><h3>Doanh thu theo tháng</h3><p className="small muted">Dữ liệu thật từ đơn hoàn thành</p></figcaption><div className="chart">{data.monthlyRevenue.map(x=><div className="chart-col" key={x.month}><span>{(Number(x.revenue)/1_000_000).toFixed(1)}</span><div className="bar" style={{height:`${Math.max(4,Number(x.revenue)/max*100)}%`}}/><span>{x.label}</span></div>)}</div></figure><figure className="card"><figcaption><h3>Cơ cấu trạng thái đơn</h3><p className="small muted">Tỷ trọng đơn trong khoảng thời gian đã chọn</p></figcaption><div className="donut" style={{background:`conic-gradient(var(--green, #2f6b12) 0 ${active/totalStatus*100}%, #c88b45 ${active/totalStatus*100}% 100%)`}}><div><strong>{data.orderCount}</strong><small>Đơn đặt nấu</small></div></div><div className="summary-line"><span>Không hủy</span><strong>{Math.round(active/totalStatus*100)}%</strong></div><div className="summary-line"><span>Đã hủy</span><strong>{Math.round(cancelled/totalStatus*100)}%</strong></div><div className="summary-line"><span>Hoàn thành</span><strong>{Math.round(completed/totalStatus*100)}%</strong></div></figure></div></>}</AdminLayout>;
}
